"""Import/Export added"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a2057276c38'
down_revision = '20240614_01'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
